### PR TITLE
Stop media compound objects

### PR DESCRIPTION
**Pull request by dcnb**
# Pull request

## Proposed changes

This revision stops video/audio/youtube/vimeo when the user clicks the next button, the previous button, or close button on a compound object modal. 

I've also added a test demo metadata that includes all media in one compound object. I'm assuming we'll delete that once this PR gets merged but thought it might be useful for your reviews, @owikle and @evanwill 

## Types of changes

- [ ] New feature (non-breaking change which adds functionality).
- [ ] Enhancement (non-breaking change which enhances functionality)
- [x] Bug Fix (non-breaking change which fixes an issue).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist

- [ ] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by dcnb** [comment]
Also this line: 

- [ ] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.

doesn't properly link to that document

**Review by owikle — APPROVED** [review]
@dcnb I tested it and it looks good to me! Thanks :)

**Comment by dcnb** [comment]
@evanwill your review is requested ...

**Comment by evanwill** [comment]
@owikle do you want to add this to CB-GH/-Sheets? :pleading_face:

**Comment by owikle** [comment]
@evanwill yeah I can do that

**Pull request merged**
