### PR TITLE
Compound objects and item page refresh

### PR DESCRIPTION
**Pull request by dcnb**
Adds compound objects options for "compound_object" and "multiple" display template, as well as "panorama" option.

### CODE REVIEW

**Comment by evanwill** [comment]
I would like to swap out object examples with public domain items

**Review by evanwill — APPROVED** [review]
@dcnb i think it is ready.

**Comment by dcnb** [comment]
@owikle you want to sign off your approval? then I'll merge the thing!

**Comment by evanwill** [comment]
@owikle did you want to add your updated compound metadata?

**Review by owikle — APPROVED** [review]
@dcnb @evanwill Ok, metadata updates are added. All looks good. Nice work!

**Comment by evanwill** [comment]
I am merging this so we can finally start working on other stuff!!

**Comment by dcnb** [comment]
@evanwill can't believe you merged this. I had dibs. See https://github.com/CollectionBuilder/collectionbuilder-csv/pull/36#issuecomment-1540909552

I HAD DIBS!!!

**Comment by evanwill** [comment]
eh. I had work to do on it, sick of waiting!

**Comment by evanwill** [comment]
p.s. @dcnb you could always go finish up the cb-docs documentation and merge that if you need that excitement!

**Pull request merged**
